git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  overrideGpg: true
promptToReturnFromSubprocess: false
gui:
  nerdFontsVersion: "3"
customCommands:
  - key: "C"
    command: 'gelf commit --yes'
    context: "files"
